version: "3.8"

services:

  seo-postgres-v2:
    container_name: seo-postgres-v2
    image: postgres:16.2
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "53321:5432"
    volumes:
      - type: bind
        source: ./data/db_data
        target: /var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 1s
      timeout: 1s
      retries: 5

  seo-optimization-v2:
    container_name: seo-optimization
    build: .
    ports:
      - "8898:8000"
    depends_on:
      seo-postgres-v2:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - curl http://0.0.0.0:8000/
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 5s

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test:
        - CMD-SHELL
        - rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 5s

  celery-worker:
    container_name: celery-worker
    build: .
    command: poetry run celery -A api.main.celery worker -l info -Q seo-classification -P eventlet
    volumes:
      - type: bind
        source: ./data/celery_data
        target: /app
    depends_on:
      seo-optimization-v2:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: poetry run celery -b amqp://guest:guest@rabbitmq:5672 inspect ping
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s

  flower:
    container_name: flower
    build: .
    command: poetry run celery -A api.main.celery flower --port=5555
    ports:
      - 55555:5555
    depends_on:
      seo-optimization-v2:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      celery-worker:
        condition: service_healthy
