version: "3.8"

services:

  seo-postgres-v2:
    container_name: seo-postgres-v2
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "53321:5432"
    volumes:
      - type: bind
        source: ./data/db_data
        target: /var/lib/postgresql/data

  seo-optimization:
    container_name: seo-optimization
    build: .
    ports:
      - "8898:8000"
